import Head from "next/head";
import { RecoilRoot } from "recoil";
import ThreeCanvas from "../components/ThreeCanvas";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          id="root"
          style={{
            width: "100vw",
            height: "100vh",
            backgroundColor: "#0E1C2F",
          }}
        >
          <ThreeCanvas></ThreeCanvas>
        </div>
      </main>
    </div>
  );
}
